# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Jul 19 23:43:03 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 554)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 61, 17))
        self.label_2.setObjectName("label_2")
        self.cmblang1 = QtGui.QComboBox(self.centralwidget)
        self.cmblang1.setGeometry(QtCore.QRect(100, 10, 111, 26))
        self.cmblang1.setObjectName("cmblang1")
        self.cmblang2 = QtGui.QComboBox(self.centralwidget)
        self.cmblang2.setGeometry(QtCore.QRect(290, 10, 111, 26))
        self.cmblang2.setObjectName("cmblang2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.label_3.setObjectName("label_3")
        self.txtKeyword = QtGui.QLineEdit(self.centralwidget)
        self.txtKeyword.setGeometry(QtCore.QRect(100, 40, 291, 22))
        self.txtKeyword.setObjectName("txtKeyword")
        self.btnSearch = QtGui.QPushButton(self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(450, 20, 113, 32))
        self.btnSearch.setObjectName("btnSearch")
        self.btnPrev = QtGui.QPushButton(self.centralwidget)
        self.btnPrev.setGeometry(QtCore.QRect(120, 480, 113, 32))
        self.btnPrev.setObjectName("btnPrev")
        self.btnNext = QtGui.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(300, 480, 113, 32))
        self.btnNext.setObjectName("btnNext")
        self.lblTotal = QtGui.QLabel(self.centralwidget)
        self.lblTotal.setGeometry(QtCore.QRect(250, 490, 61, 17))
        self.lblTotal.setObjectName("lblTotal")
        self.tblResult = QtGui.QTableWidget(self.centralwidget)
        self.tblResult.setGeometry(QtCore.QRect(10, 70, 601, 401))
        self.tblResult.setObjectName("tblResult")
        self.tblResult.setColumnCount(0)
        self.tblResult.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName("menuCorpus")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtGui.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuCorpus.addAction(self.actionBrowse)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btnSearch, QtCore.SIGNAL("clicked()"), MainWindow.searchClicked)
        QtCore.QObject.connect(self.actionBrowse, QtCore.SIGNAL("triggered()"), MainWindow.browseCorpusClicked)
        QtCore.QObject.connect(self.btnPrev, QtCore.SIGNAL("clicked()"), MainWindow.prevClicked)
        QtCore.QObject.connect(self.btnNext, QtCore.SIGNAL("clicked()"), MainWindow.nextClicked)
        QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL("triggered()"), MainWindow.loadClicked)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), MainWindow.saveClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Lang 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Lang 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Search Form", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrev.setText(QtGui.QApplication.translate("MainWindow", "Prev 100", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setText(QtGui.QApplication.translate("MainWindow", "Next 100", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTotal.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCorpus.setTitle(QtGui.QApplication.translate("MainWindow", "Corpus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))

